## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np

In [14]:
matrix1 = ([1,2,3],[4 ,5,6],[7 ,8,9]) 
matrix2 = ([5,8,6],[2,4,1],[7,2,3]) 
   
np.dot(matrix1,matrix2) 
  


array([[ 30,  22,  17],
       [ 72,  64,  47],
       [114, 106,  77]])

## Write a NumPy program to compute the determinant of a given square array

In [30]:
arr=[[1,2,3],[4,5,6],[7,8,9]]

In [31]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

## Write a NumPy program to compute the cross product of two given vectors

In [16]:
x = [[1, 2], [3, 4]]
y = [[5, 6], [7, 8]]
  
np.cross(x, y)

array([-4, -4])

## Write a NumPy program to compute the condition number of a given matrix

In [23]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [24]:
np.linalg.cond()

TypeError: _cond_dispatcher() missing 1 required positional argument: 'x'

## Write a NumPy program to compute the inverse of a given matrix

In [26]:



invers= np.array([[1, 2, 3],
                  [4, 5, 6],
                  [-7, -8, 9]])



In [29]:
print(np.linalg.inv(invers))

[[ 0.16964286 -0.00892857 -0.01785714]
 [ 0.29464286 -0.38392857  0.23214286]
 [-0.3125      0.4375     -0.125     ]]
